version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    volumes:
      - ${DATA_PATH}/db_data:/var/lib/postgresql/data
    secrets:
      - POSTGRES_PASSWORD
    networks:
      - transcendence-network

  backend:
    build: ./requirements/backend
    container_name: backend
    depends_on:
      - postgres
    networks:
      - transcendence-network

  # frontend:
  #   build: ./requirements/frontend
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - transcendence-network

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - "8443:443"
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./site:/usr/share/nginx/html
      - ../secrets/certs:/etc/ssl/private
    depends_on:
      - backend
    networks:
      - transcendence-network

volumes:
  db_data:
    external: true

networks:
  transcendence-network:
    driver: bridge

secrets:
  POSTGRES_PASSWORD:
    file: ../secrets/POSTGRES_PASSWORD.txt
