version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
    volumes:
      - ${DATA_PATH}/db_data:/var/lib/mysql
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    networks:
      - transcendence-network

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - "8443:443"
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./site:/usr/share/nginx/html
      - ../secrets/certs:/etc/ssl/private
    networks:
      - transcendence-network

volumes:
  db_data:
    external: true

networks:
  transcendence-network:
    driver: bridge

secrets:
  MYSQL_ROOT_PASSWORD:
    file: ../secrets/MYSQL_ROOT_PASSWORD.txt
  MYSQL_PASSWORD:
    file: ../secrets/MYSQL_PASSWORD.txt